export const INITIALISE = "INTIALISE_STATE";
export const INITIALISEMENU = "INTIALISE_STATE_MENU";
export const GETNEWSEARCH = "GET_NEW_SEARCH_STATE";
export const SETNEWSEARCH = "SET_NEW_SEARCH_STATE";
export const GETUPDATEDSEARCH = "GET_UPDATED_SEARCH_STATE";




export const SETSELECTEDFILTER = "SET_SELECTED_FILTER_STATE";



export const CLEARSELECTEDALLFILTER = "CLEAR_ALL_SELECTED_FILTER_STATE";
export const CLEARGROUPFILTER = "CLEAR_GROUP_FILTER_STATE";
export const GETSEARCHPAGE = "GET_SEARCH_PAGE";
export const GETFILTEREDSEARCHPAGE = "GET_FILTERED_SEARCH_PAGE";



export const KEYWORDSEARCH = "KEYWORD_SEARCH";
export const CHANGEPRICERANGE = "CHANGE_PRICE_RANGE"